version: "3.8"
services:
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - uploaded-files:/backend/books

  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tracking
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

    
     
volumes:
  app-db-data:
  uploaded-files: